# Generated by Django 2.2.2 on 2019-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoVoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPlanoVoo', models.CharField(max_length=10)),
                ('idAeronave', models.CharField(max_length=10)),
                ('tipoAeronave', models.CharField(max_length=50)),
                ('velocidadeCruzeiro', models.DecimalField(decimal_places=3, max_digits=5)),
                ('data', models.DateField()),
            ],
        ),
    ]
