# Generated by Django 2.2.2 on 2019-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_voo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planovoo',
            name='velocidadeCruzeiro',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
