# Generated by Django 2.2.2 on 2019-06-23 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_voo', '0002_auto_20190621_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='planovoo',
            name='aerodromoAlternativo',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='aerodromoDestino',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='aerodromoPartida',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='autonomiaHora',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='autonomiaMinutos',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='corMarca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='duracaoHora',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='duracaoMinutos',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='equipamentoCapacidade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='nivel',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='numeroDeAeronaves',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='outrosDados',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='pessoasABordo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='piloto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planovoo',
            name='rota',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='planovoo',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='planovoo',
            name='idAeronave',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Somente caracterres alfanumericos')]),
        ),
        migrations.AlterField(
            model_name='planovoo',
            name='idPlanoVoo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='planovoo',
            name='tipoAeronave',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Somente caracterres alfanumericos')]),
        ),
        migrations.AlterField(
            model_name='planovoo',
            name='velocidadeCruzeiro',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
