# Generated by Django 2.2.2 on 2019-06-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_voo', '0004_auto_20190630_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planovoo',
            name='aerodromoAlternativo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
