# Generated by Django 2.2.2 on 2019-07-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planos_voo', '0005_auto_20190630_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planovoo',
            old_name='duracaoHora',
            new_name='duracaoHoras',
        ),
    ]
