# Generated by Django 2.2.2 on 2019-06-23 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_comunicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrocomunicacao',
            options={'ordering': ('data',)},
        ),
    ]
