# Generated by Django 2.2.2 on 2019-06-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_comunicacao', '0003_registrocomunicacao_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocomunicacao',
            name='username',
        ),
    ]
