# Generated by Django 2.2.2 on 2019-06-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes_voo', '0008_remove_informacoesvoo_registrocomunicacao'),
        ('registro_comunicacao', '0004_remove_registrocomunicacao_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomunicacao',
            name='informacoesVoo',
            field=models.ManyToManyField(to='informacoes_voo.InformacoesVoo'),
        ),
    ]
