# Generated by Django 2.2.2 on 2019-06-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_comunicacao', '0001_initial'),
        ('informacoes_voo', '0002_auto_20190606_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesvoo',
            name='registroComunicacao',
        ),
        migrations.AddField(
            model_name='informacoesvoo',
            name='registroComunicacao',
            field=models.ManyToManyField(to='registro_comunicacao.registroComunicacao'),
        ),
    ]
