# Generated by Django 2.2.2 on 2019-06-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes_voo', '0003_auto_20190606_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesvoo',
            name='idInfo',
            field=models.TextField(null=True),
        ),
    ]
