# Generated by Django 2.2.2 on 2019-06-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_voo', '0003_remove_eventovoo_informacoesvoo'),
        ('informacoes_voo', '0005_remove_informacoesvoo_registrocomunicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesvoo',
            name='eventoVoo',
            field=models.ManyToManyField(to='eventos_voo.EventoVoo'),
        ),
    ]
