# Generated by Django 2.2.2 on 2019-06-30 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes_voo', '0007_informacoesvoo_registrocomunicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacoesvoo',
            name='registroComunicacao',
        ),
    ]
