# Generated by Django 2.2.2 on 2019-07-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes_voo', '0008_remove_informacoesvoo_registrocomunicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacoesvoo',
            old_name='eventoVoo',
            new_name='eventosVoo',
        ),
    ]
