# Generated by Django 2.2.2 on 2019-07-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes_voo', '0009_auto_20190701_0222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacoesvoo',
            old_name='idInfo',
            new_name='Info',
        ),
    ]
