# Generated by Django 2.2.2 on 2019-07-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes_voo', '0010_auto_20190701_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoesvoo',
            name='eventosVoo',
            field=models.ManyToManyField(blank=True, to='eventos_voo.EventoVoo'),
        ),
        migrations.AlterField(
            model_name='informacoesvoo',
            name='planosVoo',
            field=models.ManyToManyField(blank=True, to='planos_voo.PlanoVoo'),
        ),
    ]
