# Generated by Django 2.2.2 on 2019-06-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes_voo', '0005_remove_informacoesvoo_registrocomunicacao'),
        ('eventos_voo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventovoo',
            name='informacoesVoo',
        ),
        migrations.AddField(
            model_name='eventovoo',
            name='informacoesVoo',
            field=models.ManyToManyField(to='informacoes_voo.InformacoesVoo'),
        ),
    ]
