# Generated by Django 2.2.2 on 2019-06-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_voo', '0002_auto_20190630_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventovoo',
            name='informacoesVoo',
        ),
    ]
